sudo: required
language: python
python:
  - "3.5"
  - "3.6"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  #- "pypy"
# command to install dependencies
install:
  - pip install .
  #- pip install -r requirements.txt
# command to run tests
script: nosetests

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9da87f9fb77e9c13620d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
